### PR TITLE
Add FiveM Lua resource

### PR DESCRIPTION
**Pull request by FirstWiseman**
Added Saltychat Fivem Lua to the Available Resources

### CODE REVIEW

**Comment by BlackFlash5** [comment]
Great to see someone converting the resource for the Lua lovers out there and try to keep it compatible with the C# version!
I skipped a bit through the repo and found a few little things that need attention:
- The `SendMessage`-function for a player on the server side seems to trigger a [custom event](https://github.com/FirstWiseman/saltychat-fivem-lua/blob/eb194201dd2b757068a576a78ea22eec2bb4586f/server/Player.lua#L49) on the client, which most ppl probably don't have
- When [processing radio towers](https://github.com/FirstWiseman/saltychat-fivem-lua/blob/fa45a45d6f56469d3b11b7a3d02565c5e923a6d1/server/VoiceManager.lua#L295) you are checking the length of the whole array (`towers` - `float[][]`) instead of a single tower (`tower` - `float[]`)
- OneSync legacy doesn't support state bags, which makes it incompatible with the script, but is still [accepted by the script](https://github.com/FirstWiseman/saltychat-fivem-lua/blob/fa45a45d6f56469d3b11b7a3d02565c5e923a6d1/server/VoiceManager.lua#L514) (that's something we need to update in our script as well). You also don't notify when 1s mode is incompatible
- Server commands like `setalive` are debug commands and only available when using a debug build, you should have a way enable/disable them
- A [custom notify](https://github.com/FirstWiseman/saltychat-fivem-lua/blob/fa45a45d6f56469d3b11b7a3d02565c5e923a6d1/client/VoiceManager.lua#L723) on the client, which most ppl probably don't have
- Some links in your readme are referencing our repo (e.g. setup steps > release, setup steps > 4 (keybinds))

**Comment by FirstWiseman** [comment]
Great to hear that. Thanks for the  report about the little things that i have, appreciate it.

I have made the changes now, except for the OneSync thing that you have mentioned, because i dont really understand exactly what you want or what needs to be changed.

**Comment by BlackFlash5** [comment]
You should only accept `on` when checking the `onesync`-var, since OneSync infinity is required for state bags to function.
`legacy` and `off` can't be accepted, the script wont function as intended and a console message should be displayed.

The link for default keybinds (Setup Steps > 4.) is still linking to our repo.
For proper use of notifications you can look into the [C# implementation](https://github.com/citizenfx/fivem/blob/37639cddcb2e5b0ef05f96d5a482b236b7349a1e/code/client/clrcore/External/Screen.cs#L299), your new notification for voice range change probably doesn't work.

**Comment by FirstWiseman** [comment]
I have made these changes now. And the Notifications work perfectly fine this way. Here is a Screenshot
image

**Pull request merged**
